services:
  kmartin-web-development:
    restart: always
    image: kmartin-web-development
    container_name: kmartin-web-development
    build:
      context: .
      args:
        PROFILE: dev
    ports:
      - "4200:80"
