version: "3"
services:
  kmartin-web:
    restart: always
    image: kmartin-web
    container_name: kmartin-web
    build:
      context: .
      args:
        - PROFILE=dev # Accepts dev, prod
    ports:
      - "4200:80"
